### ISSUE TITLE
Blank messages in overlay. Bug caused / relies on 7tv

### ISSUE THREAD

**Issue by chriskgames** [r0808914/Kick-Chat-Flusher#11]
As shown in the image, messages are not showing. This temporarily fixes if you leave the stream on in the background and click on another tab. Upon coming back some messages (the ones loaded when you were not focused on stream show up properly) but then the bug returns, once you re-focus on the kick tab. When 7tv is disables the chats show properly while focused on the tab. So I suspect it has to do with 7tv.
Note: This bug happens in both chrome and firefox.
<img width="433" alt="image" src="https://github.com/user-attachments/assets/21f7ba3d-a0a7-489d-b5dc-57f93c82f9dc">

**Comment by r0808914** [comment]
This change should ensure that messages are copied correctly from the native chat using 7TV.

Commit: dbc8ebafbac1a95d212cceadd019bf51f97346e0

Please check and let me know if you still encounter any issues in Chrome and Firefox.
Download: [kick_chat_flusher-build-7tv.zip](https://github.com/user-attachments/files/17530322/kick_chat_flusher-build-7tv.zip)

[How To Load an unpacked extension](https://developer.chrome.com/docs/extensions/get-started/tutorial/hello-world#load-unpacked)
