### ISSUE TITLE
Overlay mode doesn't stay off

### ISSUE THREAD

**Issue by lkishawi3** [r0808914/Kick-Chat-Flusher#3]
When turning off the overlay if you change to theatre mode or full screen it reappears, can fix it by turning on and back off again.

**Comment by r0808914** [comment]
Replaced localStorage with chrome storage api. Enable value should now be persistently stored in version 0.8.6 (pending review). 
[storage menu.js](https://github.com/r0808914/Kick-Chat-Flusher/commit/a9248283e8a100d581a4c25b37ee63ff375e9bd2#diff-1a9452532101e8d5a2a095594747d29f718e3d25718b7e9733bfa7c4433987bf)
