### ISSUE TITLE
Not all messages show up

### ISSUE THREAD

**Issue by Sam-297** [r0808914/Kick-Chat-Flusher#4]
**(`flush` feature turned off)**

Not all messages appear on screen. It simply skips more than half the messages, like it can't keep up. 

I noticed that it mostly happens on live, around 65% of the messages don't show up.
It's almost like the chat window pauses.
I can clearly notice this when opening a stream in theatre mode, I can clearly see the extension's chat missing a lot of the messages present in the actual chat on the right.

It sometimes also happens on VOD, where around 1% dont show sometimes.

I notice the issue on lives with big channels such as xQc, but also medium channels such as Omie.

Tried turning on and off the spam feature and i noticed no difference.

I used brave (with built-in adblocker) on windows 11 and I have the 7tv extension enabled.
Tried turning off adblock, but I still notice the issue.

**Comment by r0808914** [comment]
I've tested Flusher with 7tv on both Linux and Windows 11 using Brave, but I didn't immediately notice any issues.

Do none of the buttons work, such as saving values and setting user values on page load? (see https://github.com/r0808914/Kick-Chat-Flusher/issues/3)
Have you tried reinstalling the addon and checking the console for Chat Flusher errors, especially after pressing any button?

In the latest version, Show Spam mode is set as default, so spam should always be visible even if buttons aren't working.
I haven't yet monitored xQc's fast-moving chat, but I expect most messages would be shown.

**Comment by Sam-297** [comment]
All buttons are always clickable and work fine.
However, as you can see in the pictures below, some messages are shown in the extension, while most others are simply skipped.
I tried uninstalling and saw no difference. I also noticed that it happens no matter the amount of chatters/viewers.

![Screenshot 2024-03-26 204705](https://github.com/r0808914/Kick-Chat-Flusher/assets/118610398/b55be05b-1df9-4098-b107-52c7c633b55a)

In the top photo, you can see the `junosca: well` message show, then it skips 6 messages, then it shows `VFL865: Well... uhm...` and then it continues to skip messages. 

![image](https://github.com/r0808914/Kick-Chat-Flusher/assets/118610398/95cf99dd-9b66-4a5b-92ed-07b96d4e444a)

Here is another example of it happening.

**Comment by r0808914** [comment]
Yes, you are correct. I looked into xQc's stream and discovered that indeed some messages are missing on my end. I'll try to investigate further.

![image](https://github.com/r0808914/Kick-Chat-Flusher/assets/62907735/ca81ed85-7271-489d-90ad-c9fead031760)

**Comment by r0808914** [comment]
Hello, I've implemented detection for message changes, so now all modifications should be captured, including missing messages. At least on my end, it seems that everything is working as expected. Could you please test the latest build and confirm if all messages are displayed correctly now?

![screen](https://github.com/r0808914/Kick-Chat-Flusher/assets/62907735/f3f7ea68-f434-4d32-881d-54863e1ea5c4)

development build: [kick_chat_flusher-0.9.6.zip](https://github.com/r0808914/Kick-Chat-Flusher/files/14789322/kick_chat_flusher-0.9.6.zip)

1. Download the extension zip file. 
2. Extract the zip file contents.
3. Open your browser and go to the extensions or addons page.
4. Enable developer mode.
5. Click on "Load unpacked" or similar option.
6. Select the extracted extension folder.
7. The extension should now be loaded and active in your browser.

**Comment by Sam-297** [comment]
I can confirm that all messages are displayed correctly now. Well done.
