### ISSUE TITLE
[Request] Resizing window improvement and placement saving

### ISSUE THREAD

**Issue by Sam-297** [r0808914/Kick-Chat-Flusher#6]
**All of theses features requests are for the extension used without the `flush` feature**

-Add a way to manually size the window's height. (With an input in pixels or with a mouse)
Personally, none of the presets for sizes work for me.

-The extensions remember the last placement, so the user doesn't have to reajust everytime they go in and out of fullscreen.
It should also save the height/width set manually by the user.

**Comment by r0808914** [comment]
Originally, you could resize the chat box by dragging the bottom right corner. It seems you might have missed the small resize option provided by the browser by default. So, in version 0.9.5, I added a larger resize handle for better visibility. 

I've also started working on saving the chat box position based on the channel and screen mode (like fullscreen or theater). 

Can you check if this works on your end? Also, I'm not sure if adding resizing by pixels is really necessary given the current functionality, but I'm open to adding it if you think it's useful.

**Comment by Sam-297** [comment]
It seems like the resize feature works really well and it also saves the position of the chatbox per channel. It's perfect for me.
