### ISSUE TITLE
[Request] Add Shortcut to toggle overlay

### ISSUE THREAD

**Issue by Sam-297** [r0808914/Kick-Chat-Flusher#7]
It would be nice if the extension could be toggled (enabled/disabled) with a shortcut (maybe `alt+c`, just like the FS chat add-on on FrankerFaceZ.)

**Comment by r0808914** [comment]
I've added some basic keybindings to the latest build.

![image](https://github.com/r0808914/Kick-Chat-Flusher/assets/62907735/b4c0ad3b-b596-47a6-9854-e5c633f8bcc1)
