### ISSUE TITLE
[Request] Hide ban/unban announcement messages

### ISSUE THREAD

**Issue by Sam-297** [r0808914/Kick-Chat-Flusher#8]
A button (or another way) to hide or disable the `User banned for X minute(s) by moderator` and `User's ban expired` and all other ban related messages.

**Comment by r0808914** [comment]
I've already implemented some code regarding hiding bans in the latest build, but there are still some bugs that need fixing. I believe I may have forgotten to cancel unban messages after disabling the ban event, etc.

![image](https://github.com/r0808914/Kick-Chat-Flusher/assets/62907735/2186c169-c9bb-4897-b5d4-89686f7645fb)
